on:
  release:
    types: [published]

# Avoid running multiple pipelines concurrently to avoid overlapping releases
concurrency:
  group: main-deploy
  cancel-in-progress: false

jobs:
  download-release-asset:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.7
        with:
          tag: ${{ github.event.release.name }}
          fileName: '*.jar'
          out-file-path: 'build/libs'
      - name: List contents in build/libs
        run: ls -larh build/libs