on:
  release:
    types: [published]

# Avoid running multiple pipelines concurrently to avoid overlapping releases
concurrency:
  group: main-deploy
  cancel-in-progress: false

jobs:
  download-release-asset:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.release.name }}
    steps:
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          version: ${{ env.RELEASE_VERSION }}
          regex: true
          file: '.*\\.jar'
          target: 'build/libs'
      - name: List contents in build/libs
        run: ls -larh build/libs