on:
  release:
    types: [published]

# Avoid running multiple pipelines concurrently to avoid overlapping releases
concurrency:
  group: main-deploy
  cancel-in-progress: false

jobs:
  download-release-asset:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION=${{ github.event.release.name }}
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: "echo RELEASE_VERSION"
        run: echo "${{ env.RELEASE_VERSION }}"
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          version: ${{ github.ref_name }}
          regex: true
          file: '.*\\.jar'
          target: 'build/libs'
      - name: List contents in build/libs
        run: ls -larh build/libs