name: manual deploy ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.version
        run: |
          {
            echo "### :rocket: Deploy summary on acceptance"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Version             | ${{ inputs.version }} |"
          } >> $GITHUB_STEP_SUMMARY
